### ISSUE TITLE
Unable to download from magisk

### ISSUE THREAD

**Issue by deltaclock** [ViRb3/magisk-frida#10]
Hello,
Not sure if you are responsible for this or its magisk's fault but there seems to be an error while Magisk Manager tries to download the module, probably it cant find the zip. Just wanted to let you know.

Im using the latest Magisk 20.4 on Android 9.

Thanks for the project :+1:

**Comment by ViRb3** [comment]
I just re-downloaded and re-installed the module, works fine here. I am also running Magisk 20.4 on Android 9.

**Comment by ViRb3** [comment]
If you can re-produce this on another device or give relative logs I will be happy to take a look.

**Comment by nutterthanos** [comment]
i have tried to install it and it fails to download version 14.2.18-1 with magisk 23.0 on Android 11
