### ISSUE TITLE
how to hook another github repository publish event? 

### ISSUE THREAD

**Issue by youngerier** [ViRb3/magisk-frida#14]
I was wondering how to hook another repo describe in `README ` doc
https://github.com/ViRb3/magisk-frida#how-fast-are-frida-server-updates,
could you  tell me how to make this  😁

**Comment by ViRb3** [comment]
Hello. The hook was added by the Frida development team to their release process. It calls my GitLab repo using the [GitLab Pipeline API](https://docs.gitlab.com/ee/api/pipeline_triggers.html), which in turn runs [the Drone CI build process](https://github.com/ViRb3/magisk-frida/blob/master/.drone.yml) in this repo. I'm not sure why GitLab was necessary, it was some time ago.
