### ISSUE TITLE
[QUESTION] Difference between this module and the normal Frida Server

### ISSUE THREAD

**Issue by capt-meelo** [ViRb3/magisk-frida#2]
This is not actually an issue but just a question. What's the advantage/difference between running frida "on boot" versus manually starting it? 

I observed there are some apps that can detect if Frida is running in a device and I'm curious if this will bypass the detection.

Thanks!

**Comment by ViRb3** [comment]
There is absolutely no difference, this module is just for convenience. This being said, unfortunately it will not bypass any detection.
