### ISSUE TITLE
getRunningAppProcesses error

### ISSUE THREAD

**Issue by onesecurity** [ViRb3/magisk-frida#21]
xxx@xxxMacBook-Pro-2 ~ % frida-ps -U
`Failed to enumerate processes: cannot read property 'getRunningAppProcesses' of undefined`

[magisk-frida](https://github.com/ViRb3/magisk-frida) 15.1.17-1

**Comment by BryanGIG** [comment]
Faced same issue on Android 12.1
I also try it in Android 12.0 seems to be working fine

**Comment by ViRb3** [comment]
Can you reproduce with official Frida? Seems like a problem with Frida to me.

**Comment by Systemad** [comment]
Try attaching with pid instead 
adb shell su -c "ps -A | grep youtube"
frida -U -l frida.js -p PID
