### ISSUE TITLE
After installation, system broke

### ISSUE THREAD

**Issue by haroldxie2308** [ViRb3/magisk-frida#35]
I install the newest release 16.0.17 on my Pixel XL, Android 8.1, Magisk Version 26. I can't get into the system now, any ideas? 

adb shell logcat yields: 
...
04-21 17:13:41.408  1143  1156 I android.frameworks.sensorservice@1.0::SensorManager: getService: Will do try 141 for android.frameworks.sensorservice@1.0::ISensorManager/default in 1s...
...

**Comment by acerdevs** [comment]
прошей

**Comment by ViRb3** [comment]
There's not enough information here to let me help you I'm afraid. Chances are, this is most likely an issue with Frida and not magisk-frida. Android 8.1 is terribly outdated, I don't know if Frida supports it correctly. Please try to run frida-server through adb shell and see if it works properly. If it does, then we can proceed to troubleshoot.
