### ISSUE TITLE
Latest versions of MagiskFrida not working on Redmi 9

### ISSUE THREAD

**Issue by rc4ne** [ViRb3/magisk-frida#38]
MagiskFrida doesnt respond when being used on Rooted Redmi 9 Physical Device. Running a frida script gives Timeout. I have used versions 16.4.1-1, 16.1.3-1 Bit older versions too such as 16.0.3

Attached screenshot for frida-ps -Ua

![image](https://github.com/ViRb3/magisk-frida/assets/83397936/c3491927-c0cf-4b7f-bfe1-f9f6b2e2ffe1)

**Comment by ViRb3** [comment]
Sounds like an upstream issue with magisk. Please try https://github.com/ViRb3/magisk-frida/blob/master/TROUBLESHOOTING.md

**Comment by rc4ne** [comment]
I was able to solve the issue. Everything was compliant with the troubleshooting guidelines you shared, but Riru module was activated since I had to use Trustmealready on edxposed. Deactivating it ad a reboot worked perfectly. 

Though on sidenote, since Trustmealready is your module only, anything you can suggest to make this whole situation work? Thanks!

**Comment by ViRb3** [comment]
You can use https://github.com/ViRb3/apk-utilities/blob/master/templates/frida-snippets/ssl-unpin.js
