### ISSUE TITLE
Can kernelsu be supported?

### ISSUE THREAD

**Issue by ys1231** [ViRb3/magisk-frida#45]
Just modify the installation script to make it compatible,[patch](https://github.com/ViRb3/magisk-frida/pull/44)

**Comment by skycosth** [comment]
+1

**Comment by ys1231** [comment]
`  MAGISK_BIN="/data/adb/magisk/busybox"
  KERNELSU_BIN="/data/adb/ksu/bin/busybox"
  APATCH_BIN="/data/adb/ap/bin/busybox"

  if [ -f "$MAGISK_BIN" ]; then
    echo "- ${MAGISK_BIN} found"
    UNZIP="${MAGISK_BIN} unzip"
  elif [ -f "$KERNELSU_BIN" ]; then
    echo "- ${KERNELSU_BIN} found"
    UNZIP="${KERNELSU_BIN} unzip"
  elif [ -f "$APATCH_BIN" ]; then
    echo "- ${APATCH_BIN} found"
    UNZIP="${APATCH_BIN} unzip"
  else
    echo "- No busybox found,Use system unzip"
    UNZIP="/system/bin/unzip"
  fi`
Add support APatch or all

**Comment by ys1231** [comment]
close

**Comment by liangjaden** [comment]
目前最新版本貌似仍不支付kernelsu?
