### ISSUE TITLE
Failed to attach || frida 12.8.14

### ISSUE THREAD

**Issue by b0rn2r00t** [ViRb3/magisk-frida#5]
```
root@linux:~/frida-scripts# frida -U -p 24505
     ____
    / _  |   Frida 12.8.14 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to attach: unexpected error while attaching to process with pid 24505
```
Any solution?

**Comment by ViRb3** [comment]
Have you tried using frida-server manually? Does it have the same problem? If yes, then this is a Frida issue, not related to this project. This project is simply frida-server repackaged as a Magisk module.

**Comment by b0rn2r00t** [comment]
Thanks for the response, yup I tried running manually same issue @ViRb3

**Comment by ViRb3** [comment]
Gotcha, thanks for confirming. I will close this now since it is unrelated to this project, but feel free to move the issue to Frida's issue tracker.
