### ISSUE TITLE
Module not displayed

### ISSUE THREAD

**Issue by EickyDev** [ViRb3/magisk-frida#54]
![WX20240909-154756](https://github.com/user-attachments/assets/05585661-01b3-4b45-aaaf-744c42bcfeb7)
![WX20240909-154843@2x](https://github.com/user-attachments/assets/ae9b2b0a-5e3d-438e-83a1-f6b391db9562)
It looks like the installation was successful

**Comment by Furtif** [comment]
> ![WX20240909-154756](https://private-user-images.githubusercontent.com/62491016/365558222-05585661-01b3-4b45-aaaf-744c42bcfeb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzY5MjksIm5iZiI6MTcyNTg3NjYyOSwicGF0aCI6Ii82MjQ5MTAxNi8zNjU1NTgyMjItMDU1ODU2NjEtMDFiMy00YjQ1LWFhYWYtNzQ0YzQyYmNmZWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEwMTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NGUyOTcxNGY3MGFmMzFiNTE5Yzk3ZWI2MDg3YWIxNGU4ZGZhZGM5NjRlNDBkMTRjOTViNjMzZDQxZDA2YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cLrS7-3FhvtL-0zttp4CBiYnL6FRRNl3bswhcs0NFN4) ![WX20240909-154843@2x](https://private-user-images.githubusercontent.com/62491016/365558601-ae9b2b0a-5e3d-438e-83a1-f6b391db9562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzY5MjksIm5iZiI6MTcyNTg3NjYyOSwicGF0aCI6Ii82MjQ5MTAxNi8zNjU1NTg2MDEtYWU5YjJiMGEtNWUzZC00MzhlLTgzYTEtZjZiMzkxZGI5NTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEwMTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTM5ODE3MTJiMjlmMjQ3NzE2NjkzMDEzZTc2MTVlYTkxOWQ3ZWE5YzgyODg3NjkzMWMwNzY0NjMwMmRiMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bOZkS_HdQaLzCiCxoV76WdU8-e6akW1iwktNLoEGaNM) It looks like the installation was successful

i thinks this not install's in magisk-canary versions. @ViRb3 need review this.

**Comment by diabl0w** [comment]
same issue here on canary 27007

**Comment by kingplunky** [comment]
Same issue on on Magisk version 28000, module does not display after reboot.

**Comment by Tink2Hack** [comment]
On my Pixel 5a im facing the same issue the magisk frida is not installed and im using the latest version.

**Comment by ViRb3** [comment]
Not sure what's wrong, probably the template has changed. Anyone want to raise a PR? I don't have an Android device anymore. @enovella maybe?

**Comment by Tink2Hack** [comment]
> > > same issue here on canary 27007
> > 
> > 
> > try this https://github.com/Furtif/MagiskFrida/releases/tag/v16.5.1
> 
> good! it's work!

This wroked till last week now its not working on andorid 14.

**Comment by zackey-heuristics** [comment]
@enovella I also encountered the same issue in my environment.   
The setup where the problem occurred is as follows:

- Device: Google Pixel 7a
- OS: Android 13 (TQ3A.230901.001)
- Root: Magisk official canary v28001
- Injection: Zygisk built-in on
- Modules: [Bypass Certificate Transparency (CT) error](https://github.com/JelmerDeHen/MagiskBypassCertificateTransparencyError) + MITMProxy cert
- MagiskFrida: - Tested 16.4.10

If there's anything I can help with, I'll be happy to assist.

**Comment by StagnantChill** [comment]
Facing the same issue.

Device: OnePlus 7T
OS: Android 11 OxygenOS 11.0.4.1
Root: Magisk v28000
Injection: Zygisk built-in on
Modules: Shamiko v1.1.1 + PlayIntegrityFix v17.9 + Zygisk - LSPosed v1.9.2
MagiskFrida: - Tested 16.5.1 and 16.5.6

**Comment by Windows81** [comment]
Try adding a `module.prop` file to `./base`.

https://topjohnwu.github.io/Magisk/guides.html

**Comment by zackey-heuristics** [comment]
@enovella 
I have confirmed that MagiskFrida is working correctly in the previously reported environment using the zip file you provided.  
 Thanks!

**Comment by StagnantChill** [comment]
@enovella 
The fix works for me as well. Thanks!

**Comment by shea786** [comment]
> ![image](https://private-user-images.githubusercontent.com/14809754/383530676-a6acf834-138c-46f7-bb58-7432d5b6745c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTM3MjYsIm5iZiI6MTczMTQxMzQyNiwicGF0aCI6Ii8xNDgwOTc1NC8zODM1MzA2NzYtYTZhY2Y4MzQtMTM4Yy00NmY3LWJiNTgtNzQzMmQ1YjY3NDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEyMTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYjIxMDVmZDRjZjhkOThjMjc3NTdiZWNkMjAwMDFkOTdmNGViMzRkOGZhMzk3MGNkMGU3MTU4OGQ3MzhmNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YPsFtVAZFLmZj_T28-02sP_U1CqFCyevlmJwFtQ5MHE)
> 
> ![image](https://private-user-images.githubusercontent.com/14809754/383536363-b73e8879-c2f9-4681-af62-fc114cfcc7ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTM3MjYsIm5iZiI6MTczMTQxMzQyNiwicGF0aCI6Ii8xNDgwOTc1NC8zODM1MzYzNjMtYjczZTg4NzktYzJmOS00NjgxLWFmNjItZmMxMTRjZmNjN2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEyMTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OTE4ZWUyZWZiZDMxMjkwYjA1NDZmNTM4ZmYyN2UwYTQ1MWIyNGM4NzhjOGRhZThiZTcxYjI1NGEyZDEzYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vi2Q88fcvE9JQkYnzLg-3dZQ0Vgk_GvaToQTL2VB590)
> 
> ![image](https://private-user-images.githubusercontent.com/14809754/384148539-2bfad739-4080-4941-b47b-f051a3f35639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTM3MjYsIm5iZiI6MTczMTQxMzQyNiwicGF0aCI6Ii8xNDgwOTc1NC8zODQxNDg1MzktMmJmYWQ3MzktNDA4MC00OTQxLWI0N2ItZjA1MWEzZjM1NjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEyMTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDk0YmZiMDM4ZGUzNzMzMjYwNDRhZTNkMTRmZjEwMGUyOTQ3Y2UzODc3ZDExMDI0ZDU2NDEwY2VmNGE4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FONOp19NeV2W7l4sSteuRyFJd4dAABQytvHxqvesvq0)
> 
> ![image](https://private-user-images.githubusercontent.com/14809754/384148512-6cef22aa-ec61-41da-9107-b1bbf3e54ca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTM3MjYsIm5iZiI6MTczMTQxMzQyNiwicGF0aCI6Ii8xNDgwOTc1NC8zODQxNDg1MTItNmNlZjIyYWEtZWM2MS00MWRhLTkxMDctYjFiYmYzZTU0Y2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEyMTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNzljYzQzNWY2Mjg3NTIxMmM2ZDQ3ODFlZmFhNDIwZjI5OThjYzkyYjliMGFhOWEyNmExNTZjMjY3YWQ5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EcAnIm8xH-jocn9MIuElbg1tMJ7qGKFo7Hff3vWvAQs)
> 
> can anyone verify the fix? arm64 only (for testing purposes) [MagiskFrida.zip](https://github.com/user-attachments/files/17646435/MagiskFrida.zip)
> 
> /cc @StagnantChill @zackey-heuristics @Windows81 @ViRb3 @kingplunky @diabl0w @Furtif

I can confirm that this is working as expected on my Pixel 7 Pro on Android 14

**Comment by NULL0B** [comment]
Hi, @ViRb3 the issue presists in AVD Android 13, 15 Magisk 28

**Comment by ViRb3** [comment]
Released here: https://github.com/ViRb3/magisk-frida/releases/tag/16.5.9-2

Thanks @enovella!
