### ISSUE TITLE
Update to new Magisk format

### ISSUE THREAD

**Issue by ViRb3** [ViRb3/magisk-frida#8]
https://topjohnwu.github.io/Magisk/guides.html

**Comment by enovella** [comment]
I can help you @ViRb3. Btw, I tested it on Android 11 with successful results!

**Comment by ViRb3** [comment]
Glad to hear that it works on Android 11! I don't have any particular difficulty fixing this issue, I haven't done it mainly because "if it ain't broke don't fix it". That being said, PRs are welcome :)

**Comment by enovella** [comment]
Latest Android 11 DP4 working well on latest Frida version:
```sh
tmp/platform-tools/adb shell su -c ls /system/bin | grep -q frida-server
tmp/platform-tools/adb shell su -c ps -A | grep -q frida-server
```

**Comment by ViRb3** [comment]
Superseded by #20.
